Debug 13

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,10 +11,48 @@ runs:
     - name: Collect info
       id: info
       run: |
+        # Go
+        GO_INSTALLED=$(if command -v go >/dev/null 2>&1; then echo true; else echo false; fi)
+        echo "GO_INSTALLED=$GO_INSTALLED" >> $GITHUB_OUTPUT
+        if [[ $GO_INSTALLED == 'false' ]]; then
+          if [[ "${{ runner.os }}" == "Linux" ]]; then
+            BIN_1=linux
+          elif [[ "${{ runner.os }}" == "macOS" ]]
+            BIN_1=darwin
+          else
+            BIN_1=windows
+          fi
+          if [[ "${{ runner.arch }}" == "X86" ]]; then
+            BIN_2=386
+          elif [[ "${{ runner.os }}" == "X64" ]]
+            BIN_2=amd64
+          elif [[ "${{ runner.os }}" == "ARM64" ]]
+            BIN_2=arm64
+          else
+            echo "::error title=Unsupported OS::${{ runner.os }} ${{ runner.arch }} is not supported"
+            exit 1
+          fi
+          echo "GO_BINARY=$BIN_1-$BIN_2" >> $GITHUB_OUTPUT
+        fi
+        mkdir -p "$GITHUB_WORKSPACE/go"
+        echo "GO_PATH=$GITHUB_WORKSPACE/go" >> $GITHUB_OUTPUT
+        # Cloe
         CLOE_INSTALLED=$(if command -v cloe >/dev/null 2>&1; then echo true; else echo false; fi)
         echo "CLOE_INSTALLED=$CLOE_INSTALLED" >> $GITHUB_OUTPUT
         mkdir -p "$GITHUB_WORKSPACE/cloe"
         echo "CLOE_PATH=$GITHUB_WORKSPACE/cloe" >> $GITHUB_OUTPUT
+      shell: sh
+    - name: Install go
+      if: ${{ steps.info.outputs.GO_INSTALLED == 'false' }}
+      env:
+        DOWNLOAD_URL: https://go.dev/dl/go1.19.3.${{ steps.info.outputs.GO_BINARY }}.tar.gz 
+      run: |
+        echo "before (Go):"
+        ls -A
+        wget -c $DOWNLOAD_URL -O - | tar -xz
+        echo "after (Go):"
+        ls -A
+        echo "${{ steps.info.outputs.GO_PATH }}" >> $GITHUB_PATH
       shell: sh
     - name: Download Cloe
       if: ${{ steps.info.outputs.CLOE_INSTALLED == 'false' }}
@@ -25,7 +63,12 @@ runs:
         path: cloe
     - name: Install cloe
       if: ${{ steps.info.outputs.CLOE_INSTALLED == 'false' }}
-      run: rake build
+      run: |
+        echo "before (cloe)"
+        ls -A
+        rake build
+        echo "after (cloe)"
+        ls -A
       shell: sh
       working-directory: ${{ steps.info.outputs.CLOE_PATH }}
 #    - name: Install cloe
